/* Generated by JSIL v0.8.2 build 30747. See http://jsil.org/ for more information. */ 
'use strict';
var $asm_Studie = JSIL.DeclareAssembly("Studie, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

/* class ??Studie??Component??App??Xaml??Factory */ 

(function $1c0$1c0Studie$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.TypeInstantiationHelper)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_Studie.Studie.App)) ();
  };

  function $1c0$1c0Studie$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory_Instantiate () {
    return $T00()['Instantiate']($T01().__Type__);
  };

  JSIL.MakeStaticClass("\u01c0\u01c0Studie\u01c0\u01c0Component\u01c0\u01c0App\u01c0\u01c0Xaml\u01c0\u01c0Factory", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:true , Public:true }, "Instantiate", 
      JSIL.MethodSignature.Return($.Object), 
      $1c0$1c0Studie$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory_Instantiate
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class ??Studie??Component??Mainpage??Xaml??Factory */ 

(function $1c0$1c0Studie$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.TypeInstantiationHelper)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_Studie.Studie.MainPage)) ();
  };

  function $1c0$1c0Studie$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory_Instantiate () {
    return $T00()['Instantiate']($T01().__Type__);
  };

  JSIL.MakeStaticClass("\u01c0\u01c0Studie\u01c0\u01c0Component\u01c0\u01c0Mainpage\u01c0\u01c0Xaml\u01c0\u01c0Factory", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:true , Public:true }, "Instantiate", 
      JSIL.MethodSignature.Return($.Object), 
      $1c0$1c0Studie$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory_Instantiate
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("Studie");
/* class Studie.App */ 

(function App$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Application)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_Studie.Studie.MainPage)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Window)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.StartupAssemblyInfo)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.ResourceDictionary)) ();
  };

  function App__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    var content = new ($T01())();
    $T02().Window$Current$value['set_Content'](content);
  };

  function App_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      if (false) {
        $T03().$Cast(this).XamlSourcePath = "Studie\\App.xaml";
      }
      $T04().OutputRootPath = "Output\\";
      $T04().OutputAppFilesPath = "app-cshtml5\\app\\";
      $T04().OutputLibrariesPath = "app-cshtml5\\libs\\";
      $T04().OutputResourcesPath = "app-cshtml5\\res\\";
      var resources = new ($T05())();
      this['set_Resources'](resources);
      this['set_Resources'](resources);
    }
  };

  JSIL.MakeType({
      BaseType: $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Application"), 
      Name: "Studie.App", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      App__ctor
    );

    $.Method({Static:false, Public:true }, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      App_InitializeComponent
    );

    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class Studie.MainPage */ 

(function MainPage$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Page)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Primitives.ToggleButton)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_mscorlib.System.Boolean)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm_mscorlib.System.Int32)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm_mscorlib.System.Object)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.FrameworkElement)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.MessageBox)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_mscorlib.System.Object))) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ItemsControl)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Primitives.Selector)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm_mscorlib.System.Exception)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.TextBox)) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm_mscorlib.System.Convert)) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize(System.Array.Of($asm_mscorlib.System.String))) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm_mscorlib.System.FormatException)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm_CSharpXamlForHtml5_System_dll.System.Net.WebClient)) ();
  };
  var $T12 = function () {
    return ($T12 = JSIL.Memoize($asm_mscorlib.System.Text.Encoding)) ();
  };
  var $T13 = function () {
    return ($T13 = JSIL.Memoize($asm_CSharpXamlForHtml5_System_dll.System.Net.WebHeaderCollection)) ();
  };
  var $T14 = function () {
    return ($T14 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement)) ();
  };
  var $T15 = function () {
    return ($T15 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Grid)) ();
  };
  var $T16 = function () {
    return ($T16 = JSIL.Memoize($asm_mscorlib.System.Double)) ();
  };
  var $T17 = function () {
    return ($T17 = JSIL.Memoize($asm_CSharpXamlForHtml5.DotNetForHtml5.Core.TypeFromStringConverters)) ();
  };
  var $T18 = function () {
    return ($T18 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.RowDefinition)) ();
  };
  var $T19 = function () {
    return ($T19 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.GridLength)) ();
  };
  var $T1A = function () {
    return ($T1A = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.RowDefinition))) ();
  };
  var $T1B = function () {
    return ($T1B = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ColumnDefinition)) ();
  };
  var $T1C = function () {
    return ($T1C = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ColumnDefinition))) ();
  };
  var $T1D = function () {
    return ($T1D = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.CheckBox)) ();
  };
  var $T1E = function () {
    return ($T1E = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.UserControl)) ();
  };
  var $T1F = function () {
    return ($T1F = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.VerticalAlignment)) ();
  };
  var $T20 = function () {
    return ($T20 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.HorizontalAlignment)) ();
  };
  var $T21 = function () {
    return ($T21 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ContentControl)) ();
  };
  var $T22 = function () {
    return ($T22 = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement))) ();
  };
  var $T23 = function () {
    return ($T23 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Panel)) ();
  };
  var $T24 = function () {
    return ($T24 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ComboBox)) ();
  };
  var $T25 = function () {
    return ($T25 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Thickness)) ();
  };
  var $T26 = function () {
    return ($T26 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ComboBoxItem)) ();
  };
  var $T27 = function () {
    return ($T27 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Button)) ();
  };
  var $T28 = function () {
    return ($T28 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Primitives.ButtonBase)) ();
  };
  var $T29 = function () {
    return ($T29 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventHandler)) ();
  };
  var $T2A = function () {
    return ($T2A = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ScrollViewer)) ();
  };
  var $T2B = function () {
    return ($T2B = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ListBox)) ();
  };
  var $T2C = function () {
    return ($T2C = JSIL.Memoize($asm_mscorlib.System.Collections.Generic.List$b1.Of($asm_Studie.Studie.MainPage_CrystaInfo))) ();
  };
  var $T2D = function () {
    return ($T2D = JSIL.Memoize($asm_mscorlib.System.Char)) ();
  };
  var $T2E = function () {
    return ($T2E = JSIL.Memoize($asm_Studie.Studie.MainPage_CrystaInfo)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm_mscorlib.TypeRef("System.Exception"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.MethodSignature($asm_mscorlib.TypeRef("System.Int32"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm_mscorlib.TypeRef("System.String"), $asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(new JSIL.MethodSignature($asm_mscorlib.TypeRef("System.String"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(new JSIL.ConstructorSignature($asm_mscorlib.TypeRef("System.Collections.Generic.List`1", [$asm_Studie.TypeRef("Studie.MainPage+CrystaInfo")]), null))) ();
  };

  function MainPage__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    this['Set_FilterIndex']();
    var isChecked = true;
    (this.SpecialCheckBoxEx.IsChecked = isChecked);
    (this.NormCheckBox.IsChecked = (this.NormCheckBoxEx.IsChecked = (this.WeaponCheckBox.IsChecked = (this.WeaponCheckBoxEx.IsChecked = (this.ArmorCheckBox.IsChecked = (this.ArmorCheckBoxEx.IsChecked = (this.AdditionalCheckBox.IsChecked = (this.AdditionalCheckBoxEx.IsChecked = (this.SpecialCheckBox.IsChecked = isChecked)))))))));
  };

  function MainPage_CutString (data, start, end) {
    var flag = ((data.indexOf(start)) === -1) || 
    ((data.lastIndexOf(end)) === -1);
    if (flag) {
      var result = data;
    } else {
      result = (data.substr((((data.indexOf(start)) + (start.length | 0)) | 0), data.lastIndexOf(end)));
    }
    return result;
  };

  function MainPage_DeleteFilterBtn_Click (sender, e) {
    var flag = !(this.FilterListCombo)['get_IsEnabled']();
    if (flag) {
      $T08()['Show']("\uc0ad\uc81c\ud560 \ud544\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4");
    } else {
      ((this.FilterList)['get_Items']())['RemoveAt']((this.FilterListCombo)['get_SelectedIndex']());
      ((this.FilterListCombo)['get_Items']())['RemoveAt']((this.FilterListCombo)['get_SelectedIndex']());
      this['Set_FilterIndex']();
    }
  };

  function MainPage_FilterSet_Click (sender, e, $exception) {
    try {
      var flag = (((this.FilterOption)['get_SelectedIndex']() | 0) === -1) || 
      (((this.FilterSign)['get_SelectedIndex']() | 0) === -1) || 
      ((this.FilterValue)['get_Text']() == "");
      if (flag) {
        throw $S00().Construct("\ud544\ud130\uc758 \uac12\uc744 \uc804\ubd80 \uc124\uc815\ud574\uc8fc\uc138\uc694");
      }
      var item = (JSIL.ConcatString.apply(null, JSIL.Array.New($T02(), [((this.FilterOption)['get_SelectedValue']())['toString'](), " ", ((this.FilterSign)['get_SelectedValue']())['toString'](), " ", ($S01().CallStatic($T0E(), "ToInt32", null, (this.FilterValue)['get_Text']())).toString()])));
      ((this.FilterList)['get_Items']())['Add'](item);
      ((this.FilterListCombo)['get_Items']())['Add'](item);
      this['Set_FilterIndex']();
    } catch ($exception) {
      if ($T10().$Is($exception)) {
        $T08()['Show']("\uc815\uc218\ub9cc \uc785\ub825\ud574\uc8fc\uc138\uc694");
      } else {
        $T08()['Show']($exception['get_Message']());
      }
    }
  };

  function MainPage_GetDataFromHub (SourceUrl) {
    var webClient = new ($T11())();
    webClient.WebClient$Encoding$value = $T12()['get_UTF8']();
    $S02().CallVirtual("Add", null, webClient['get_Headers'](), "origin", "dcinside.com");
    return $S03().CallVirtual("DownloadString", null, webClient, SourceUrl);
  };

  function MainPage_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      if (this !== null) {
        $T14().$Cast(this).XamlSourcePath = "Studie\\MainPage.xaml";
      }
      var grid = new ($T15())();
      grid['set_Height']($T16().$Cast($T17()['ConvertFromInvariantString']($T16().__Type__, "640")));
      grid['set_Width']($T16().$Cast($T17()['ConvertFromInvariantString']($T16().__Type__, "360")));
      var rowDefinition = new ($T18())();
      (rowDefinition.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "3*"))['MemberwiseClone']());
      var rowDefinition2 = new ($T18())();
      (rowDefinition2.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "4*"))['MemberwiseClone']());
      var rowDefinition3 = new ($T18())();
      (rowDefinition3.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "5*"))['MemberwiseClone']());
      var rowDefinition4 = new ($T18())();
      (rowDefinition4.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid['get_RowDefinitions']())['Add'](rowDefinition);
      (grid['get_RowDefinitions']())['Add'](rowDefinition2);
      (grid['get_RowDefinitions']())['Add'](rowDefinition3);
      (grid['get_RowDefinitions']())['Add'](rowDefinition4);
      var grid2 = new ($T15())();
      $T15()['SetRow'](grid2, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      var columnDefinition = new ($T1B())();
      (columnDefinition.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition2 = new ($T1B())();
      (columnDefinition2.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid2['get_ColumnDefinitions']())['Add'](columnDefinition);
      (grid2['get_ColumnDefinitions']())['Add'](columnDefinition2);
      var rowDefinition5 = new ($T18())();
      (rowDefinition5.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition6 = new ($T18())();
      (rowDefinition6.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition7 = new ($T18())();
      (rowDefinition7.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition8 = new ($T18())();
      (rowDefinition8.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition9 = new ($T18())();
      (rowDefinition9.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid2['get_RowDefinitions']())['Add'](rowDefinition5);
      (grid2['get_RowDefinitions']())['Add'](rowDefinition6);
      (grid2['get_RowDefinitions']())['Add'](rowDefinition7);
      (grid2['get_RowDefinitions']())['Add'](rowDefinition8);
      (grid2['get_RowDefinitions']())['Add'](rowDefinition9);
      var checkBox = new ($T1D())();
      $T15()['SetRow'](checkBox, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T15()['SetColumn'](checkBox, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T1E().prototype['RegisterName'].call(this, "NormCheckBox", checkBox);
      checkBox['set_Name']("NormCheckBox");
      checkBox['set_VerticalAlignment']($T1F().Center);
      checkBox['set_HorizontalAlignment']($T20().Center);
      checkBox['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub178\ub9d0 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox2 = new ($T1D())();
      $T15()['SetRow'](checkBox2, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T15()['SetColumn'](checkBox2, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T1E().prototype['RegisterName'].call(this, "NormCheckBoxEx", checkBox2);
      checkBox2['set_Name']("NormCheckBoxEx");
      checkBox2['set_VerticalAlignment']($T1F().Center);
      checkBox2['set_HorizontalAlignment']($T20().Center);
      checkBox2['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub178\ub9d0 \uac15\ud654 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox3 = new ($T1D())();
      $T15()['SetRow'](checkBox3, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T15()['SetColumn'](checkBox3, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T1E().prototype['RegisterName'].call(this, "WeaponCheckBox", checkBox3);
      checkBox3['set_Name']("WeaponCheckBox");
      checkBox3['set_VerticalAlignment']($T1F().Center);
      checkBox3['set_HorizontalAlignment']($T20().Center);
      checkBox3['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb34\uae30 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox4 = new ($T1D())();
      $T15()['SetRow'](checkBox4, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T15()['SetColumn'](checkBox4, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T1E().prototype['RegisterName'].call(this, "WeaponCheckBoxEx", checkBox4);
      checkBox4['set_Name']("WeaponCheckBoxEx");
      checkBox4['set_VerticalAlignment']($T1F().Center);
      checkBox4['set_HorizontalAlignment']($T20().Center);
      checkBox4['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb34\uae30 \uac15\ud654 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox5 = new ($T1D())();
      $T15()['SetRow'](checkBox5, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "2")));
      $T15()['SetColumn'](checkBox5, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T1E().prototype['RegisterName'].call(this, "ArmorCheckBox", checkBox5);
      checkBox5['set_Name']("ArmorCheckBox");
      checkBox5['set_VerticalAlignment']($T1F().Center);
      checkBox5['set_HorizontalAlignment']($T20().Center);
      checkBox5['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc29\uc5b4\uad6c \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox6 = new ($T1D())();
      $T15()['SetRow'](checkBox6, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "2")));
      $T15()['SetColumn'](checkBox6, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T1E().prototype['RegisterName'].call(this, "ArmorCheckBoxEx", checkBox6);
      checkBox6['set_Name']("ArmorCheckBoxEx");
      checkBox6['set_VerticalAlignment']($T1F().Center);
      checkBox6['set_HorizontalAlignment']($T20().Center);
      checkBox6['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc29\uc5b4\uad6c \uac15\ud654 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox7 = new ($T1D())();
      $T15()['SetRow'](checkBox7, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "3")));
      $T15()['SetColumn'](checkBox7, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T1E().prototype['RegisterName'].call(this, "AdditionalCheckBox", checkBox7);
      checkBox7['set_Name']("AdditionalCheckBox");
      checkBox7['set_VerticalAlignment']($T1F().Center);
      checkBox7['set_HorizontalAlignment']($T20().Center);
      checkBox7['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ucd94\uac00 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox8 = new ($T1D())();
      $T15()['SetRow'](checkBox8, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "3")));
      $T15()['SetColumn'](checkBox8, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T1E().prototype['RegisterName'].call(this, "AdditionalCheckBoxEx", checkBox8);
      checkBox8['set_Name']("AdditionalCheckBoxEx");
      checkBox8['set_VerticalAlignment']($T1F().Center);
      checkBox8['set_HorizontalAlignment']($T20().Center);
      checkBox8['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ucd94\uac00 \uac15\ud654 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox9 = new ($T1D())();
      $T15()['SetRow'](checkBox9, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "4")));
      $T15()['SetColumn'](checkBox9, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "0")));
      $T1E().prototype['RegisterName'].call(this, "SpecialCheckBox", checkBox9);
      checkBox9['set_Name']("SpecialCheckBox");
      checkBox9['set_VerticalAlignment']($T1F().Center);
      checkBox9['set_HorizontalAlignment']($T20().Center);
      checkBox9['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud2b9\uc218 \ud06c\ub9ac\uc2a4\ud0c0"));
      var checkBox10 = new ($T1D())();
      $T15()['SetRow'](checkBox10, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "4")));
      $T15()['SetColumn'](checkBox10, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      $T1E().prototype['RegisterName'].call(this, "SpecialCheckBoxEx", checkBox10);
      checkBox10['set_Name']("SpecialCheckBoxEx");
      checkBox10['set_VerticalAlignment']($T1F().Center);
      checkBox10['set_HorizontalAlignment']($T20().Center);
      checkBox10['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud2b9\uc218 \uac15\ud654 \ud06c\ub9ac\uc2a4\ud0c0"));
      (grid2['get_Children']())['Add'](checkBox);
      (grid2['get_Children']())['Add'](checkBox2);
      (grid2['get_Children']())['Add'](checkBox3);
      (grid2['get_Children']())['Add'](checkBox4);
      (grid2['get_Children']())['Add'](checkBox5);
      (grid2['get_Children']())['Add'](checkBox6);
      (grid2['get_Children']())['Add'](checkBox7);
      (grid2['get_Children']())['Add'](checkBox8);
      (grid2['get_Children']())['Add'](checkBox9);
      (grid2['get_Children']())['Add'](checkBox10);
      var grid3 = new ($T15())();
      $T15()['SetRow'](grid3, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      var rowDefinition10 = new ($T18())();
      (rowDefinition10.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition11 = new ($T18())();
      (rowDefinition11.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "3*"))['MemberwiseClone']());
      var rowDefinition12 = new ($T18())();
      (rowDefinition12.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid3['get_RowDefinitions']())['Add'](rowDefinition10);
      (grid3['get_RowDefinitions']())['Add'](rowDefinition11);
      (grid3['get_RowDefinitions']())['Add'](rowDefinition12);
      var grid4 = new ($T15())();
      var columnDefinition3 = new ($T1B())();
      (columnDefinition3.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "7*"))['MemberwiseClone']());
      var columnDefinition4 = new ($T1B())();
      (columnDefinition4.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "2*"))['MemberwiseClone']());
      var columnDefinition5 = new ($T1B())();
      (columnDefinition5.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "3*"))['MemberwiseClone']());
      var columnDefinition6 = new ($T1B())();
      (columnDefinition6.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition3);
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition4);
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition5);
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition6);
      var comboBox = new ($T24())();
      $T1E().prototype['RegisterName'].call(this, "FilterOption", comboBox);
      comboBox['set_Name']("FilterOption");
      (comboBox.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "20,7"))['MemberwiseClone']());
      var comboBoxItem = new ($T26())();
      comboBoxItem['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "STR"));
      var comboBoxItem2 = new ($T26())();
      comboBoxItem2['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "STR%"));
      var comboBoxItem3 = new ($T26())();
      comboBoxItem3['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "INT"));
      var comboBoxItem4 = new ($T26())();
      comboBoxItem4['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "INT%"));
      var comboBoxItem5 = new ($T26())();
      comboBoxItem5['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "VIT"));
      var comboBoxItem6 = new ($T26())();
      comboBoxItem6['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "VIT%"));
      var comboBoxItem7 = new ($T26())();
      comboBoxItem7['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "AGI"));
      var comboBoxItem8 = new ($T26())();
      comboBoxItem8['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "AGI%"));
      var comboBoxItem9 = new ($T26())();
      comboBoxItem9['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "DEX"));
      var comboBoxItem10 = new ($T26())();
      comboBoxItem10['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "DEX%"));
      var comboBoxItem11 = new ($T26())();
      comboBoxItem11['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "ATK"));
      var comboBoxItem12 = new ($T26())();
      comboBoxItem12['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "ATK%"));
      var comboBoxItem13 = new ($T26())();
      comboBoxItem13['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "MATK"));
      var comboBoxItem14 = new ($T26())();
      comboBoxItem14['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "MATK%"));
      var comboBoxItem15 = new ($T26())();
      comboBoxItem15['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "DEF"));
      var comboBoxItem16 = new ($T26())();
      comboBoxItem16['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "DEF%"));
      var comboBoxItem17 = new ($T26())();
      comboBoxItem17['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "MDEF"));
      var comboBoxItem18 = new ($T26())();
      comboBoxItem18['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "MDEF%"));
      var comboBoxItem19 = new ($T26())();
      comboBoxItem19['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc548\uc815\ub960%"));
      var comboBoxItem20 = new ($T26())();
      comboBoxItem20['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uba85\uc911"));
      var comboBoxItem21 = new ($T26())();
      comboBoxItem21['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uba85\uc911%"));
      var comboBoxItem22 = new ($T26())();
      comboBoxItem22['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc808\ub300\uba85\uc911%"));
      var comboBoxItem23 = new ($T26())();
      comboBoxItem23['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud68c\ud53c"));
      var comboBoxItem24 = new ($T26())();
      comboBoxItem24['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud68c\ud53c%"));
      var comboBoxItem25 = new ($T26())();
      comboBoxItem25['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc808\ub300\ud68c\ud53c%"));
      var comboBoxItem26 = new ($T26())();
      comboBoxItem26['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud06c\ub9ac\ud2f0\uceec\ub960"));
      var comboBoxItem27 = new ($T26())();
      comboBoxItem27['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud06c\ub9ac\ud2f0\uceec\ub960%"));
      var comboBoxItem28 = new ($T26())();
      comboBoxItem28['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud06c\ub9ac\ud2f0\uceec\ub300\ubbf8\uc9c0"));
      var comboBoxItem29 = new ($T26())();
      comboBoxItem29['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud06c\ub9ac\ud2f0\uceec\ub300\ubbf8\uc9c0%"));
      var comboBoxItem30 = new ($T26())();
      comboBoxItem30['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uacf5\uaca9\uc18d\ub3c4"));
      var comboBoxItem31 = new ($T26())();
      comboBoxItem31['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uacf5\uaca9\uc18d\ub3c4%"));
      var comboBoxItem32 = new ($T26())();
      comboBoxItem32['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc2dc\uc804\uc18d\ub3c4"));
      var comboBoxItem33 = new ($T26())();
      comboBoxItem33['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc2dc\uc804\uc18d\ub3c4%"));
      var comboBoxItem34 = new ($T26())();
      comboBoxItem34['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud589\ub3d9\uc18d\ub3c4%"));
      var comboBoxItem35 = new ($T26())();
      comboBoxItem35['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ucd5c\ub300HP"));
      var comboBoxItem36 = new ($T26())();
      comboBoxItem36['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ucd5c\ub300HP%"));
      var comboBoxItem37 = new ($T26())();
      comboBoxItem37['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "HP\uc790\uc5f0\ud68c\ubcf5%"));
      var comboBoxItem38 = new ($T26())();
      comboBoxItem38['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ucd5c\ub300MP"));
      var comboBoxItem39 = new ($T26())();
      comboBoxItem39['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ucd5c\ub300MP%"));
      var comboBoxItem40 = new ($T26())();
      comboBoxItem40['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "MP\uc790\uc5f0\ud68c\ubcf5%"));
      var comboBoxItem41 = new ($T26())();
      comboBoxItem41['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uacf5\uaca9MP\ud68c\ubcf5"));
      var comboBoxItem42 = new ($T26())();
      comboBoxItem42['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uacf5\uaca9MP\ud68c\ubcf5%"));
      var comboBoxItem43 = new ($T26())();
      comboBoxItem43['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb34\uae30ATK"));
      var comboBoxItem44 = new ($T26())();
      comboBoxItem44['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb34\uae30ATK%"));
      var comboBoxItem45 = new ($T26())();
      comboBoxItem45['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb34\ub0b4\uc131%"));
      var comboBoxItem46 = new ($T26())();
      comboBoxItem46['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubd88\ub0b4\uc131%"));
      var comboBoxItem47 = new ($T26())();
      comboBoxItem47['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb3c\ub0b4\uc131%"));
      var comboBoxItem48 = new ($T26())();
      comboBoxItem48['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc14\ub78c\ub0b4\uc131%"));
      var comboBoxItem49 = new ($T26())();
      comboBoxItem49['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub545\ub0b4\uc131%"));
      var comboBoxItem50 = new ($T26())();
      comboBoxItem50['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ube5b\ub0b4\uc131%"));
      var comboBoxItem51 = new ($T26())();
      comboBoxItem51['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc5b4\ub460\ub0b4\uc131%"));
      var comboBoxItem52 = new ($T26())();
      comboBoxItem52['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb3c\ub9ac\ubc30\ub9ac\uc5b4"));
      var comboBoxItem53 = new ($T26())();
      comboBoxItem53['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub9c8\ubc95\ubc30\ub9ac\uc5b4"));
      var comboBoxItem54 = new ($T26())();
      comboBoxItem54['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ube44\uc728\ubc30\ub9ac\uc5b4%"));
      var comboBoxItem55 = new ($T26())();
      comboBoxItem55['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc30\ub9ac\uc5b4\uc18d\ub3c4%"));
      var comboBoxItem56 = new ($T26())();
      comboBoxItem56['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb3c\ub9ac\ub0b4\uc131%"));
      var comboBoxItem57 = new ($T26())();
      comboBoxItem57['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub9c8\ubc95\ub0b4\uc131%"));
      var comboBoxItem58 = new ($T26())();
      comboBoxItem58['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "Guard\ub825%"));
      var comboBoxItem59 = new ($T26())();
      comboBoxItem59['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "Guard\ub960%"));
      var comboBoxItem60 = new ($T26())();
      comboBoxItem60['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "Avoid\ub960%"));
      var comboBoxItem61 = new ($T26())();
      comboBoxItem61['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub300\ubbf8\uc9c0\ubc18\uc0ac%"));
      var comboBoxItem62 = new ($T26())();
      comboBoxItem62['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc18\uc0ac\ub300\ubbf8\uc9c0%"));
      var comboBoxItem63 = new ($T26())();
      comboBoxItem63['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc5b4\uadf8\ub85c%"));
      var comboBoxItem64 = new ($T26())();
      comboBoxItem64['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc774\uc0c1\ub0b4\uc131%"));
      var comboBoxItem65 = new ($T26())();
      comboBoxItem65['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubb3c\ub9ac\uad00\ud1b5%"));
      var comboBoxItem66 = new ($T26())();
      comboBoxItem66['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub9c8\ubc95\uad00\ud1b5%"));
      var comboBoxItem67 = new ($T26())();
      comboBoxItem67['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uadfc\uac70\ub9ac\uc704\ub825%"));
      var comboBoxItem68 = new ($T26())();
      comboBoxItem68['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc6d0\uac70\ub9ac\uc704\ub825%"));
      var comboBoxItem69 = new ($T26())();
      comboBoxItem69['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc1c\ub3c4\uacf5\uaca9"));
      var comboBoxItem70 = new ($T26())();
      comboBoxItem70['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc1c\ub3c4\uacf5\uaca9%"));
      var comboBoxItem71 = new ($T26())();
      comboBoxItem71['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc608\uce21%"));
      var comboBoxItem72 = new ($T26())();
      comboBoxItem72['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc29\uc5b4\ubb34\ub108\ub728\ub9ac\uae30%"));
      var comboBoxItem73 = new ($T26())();
      comboBoxItem73['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ubc94\uc704\uacbd\uac10%"));
      var comboBoxItem74 = new ($T26())();
      comboBoxItem74['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc8fc\uc704\uacbd\uac10%"));
      var comboBoxItem75 = new ($T26())();
      comboBoxItem75['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc0ac\uc778\uacbd\uac10%"));
      var comboBoxItem76 = new ($T26())();
      comboBoxItem76['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud0c4\ud658\uacbd\uac10%"));
      var comboBoxItem77 = new ($T26())();
      comboBoxItem77['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub3cc\uc9c4\uacbd\uac10%"));
      var comboBoxItem78 = new ($T26())();
      comboBoxItem78['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc7a5\ud310\uacbd\uac10%"));
      var comboBoxItem79 = new ($T26())();
      comboBoxItem79['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc6b4\uc11d\uacbd\uac10%"));
      var comboBoxItem80 = new ($T26())();
      comboBoxItem80['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc9c1\uc120\uacbd\uac10%"));
      var comboBoxItem81 = new ($T26())();
      comboBoxItem81['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud68d\ub4ddEXP%"));
      var comboBoxItem82 = new ($T26())();
      comboBoxItem82['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub4dc\ub78d\ub960%"));
      var comboBoxItem83 = new ($T26())();
      comboBoxItem83['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ub3c4\uad6c\uc18d\ub3c4"));
      (comboBox['get_Items']())['Add'](comboBoxItem);
      (comboBox['get_Items']())['Add'](comboBoxItem2);
      (comboBox['get_Items']())['Add'](comboBoxItem3);
      (comboBox['get_Items']())['Add'](comboBoxItem4);
      (comboBox['get_Items']())['Add'](comboBoxItem5);
      (comboBox['get_Items']())['Add'](comboBoxItem6);
      (comboBox['get_Items']())['Add'](comboBoxItem7);
      (comboBox['get_Items']())['Add'](comboBoxItem8);
      (comboBox['get_Items']())['Add'](comboBoxItem9);
      (comboBox['get_Items']())['Add'](comboBoxItem10);
      (comboBox['get_Items']())['Add'](comboBoxItem11);
      (comboBox['get_Items']())['Add'](comboBoxItem12);
      (comboBox['get_Items']())['Add'](comboBoxItem13);
      (comboBox['get_Items']())['Add'](comboBoxItem14);
      (comboBox['get_Items']())['Add'](comboBoxItem15);
      (comboBox['get_Items']())['Add'](comboBoxItem16);
      (comboBox['get_Items']())['Add'](comboBoxItem17);
      (comboBox['get_Items']())['Add'](comboBoxItem18);
      (comboBox['get_Items']())['Add'](comboBoxItem19);
      (comboBox['get_Items']())['Add'](comboBoxItem20);
      (comboBox['get_Items']())['Add'](comboBoxItem21);
      (comboBox['get_Items']())['Add'](comboBoxItem22);
      (comboBox['get_Items']())['Add'](comboBoxItem23);
      (comboBox['get_Items']())['Add'](comboBoxItem24);
      (comboBox['get_Items']())['Add'](comboBoxItem25);
      (comboBox['get_Items']())['Add'](comboBoxItem26);
      (comboBox['get_Items']())['Add'](comboBoxItem27);
      (comboBox['get_Items']())['Add'](comboBoxItem28);
      (comboBox['get_Items']())['Add'](comboBoxItem29);
      (comboBox['get_Items']())['Add'](comboBoxItem30);
      (comboBox['get_Items']())['Add'](comboBoxItem31);
      (comboBox['get_Items']())['Add'](comboBoxItem32);
      (comboBox['get_Items']())['Add'](comboBoxItem33);
      (comboBox['get_Items']())['Add'](comboBoxItem34);
      (comboBox['get_Items']())['Add'](comboBoxItem35);
      (comboBox['get_Items']())['Add'](comboBoxItem36);
      (comboBox['get_Items']())['Add'](comboBoxItem37);
      (comboBox['get_Items']())['Add'](comboBoxItem38);
      (comboBox['get_Items']())['Add'](comboBoxItem39);
      (comboBox['get_Items']())['Add'](comboBoxItem40);
      (comboBox['get_Items']())['Add'](comboBoxItem41);
      (comboBox['get_Items']())['Add'](comboBoxItem42);
      (comboBox['get_Items']())['Add'](comboBoxItem43);
      (comboBox['get_Items']())['Add'](comboBoxItem44);
      (comboBox['get_Items']())['Add'](comboBoxItem45);
      (comboBox['get_Items']())['Add'](comboBoxItem46);
      (comboBox['get_Items']())['Add'](comboBoxItem47);
      (comboBox['get_Items']())['Add'](comboBoxItem48);
      (comboBox['get_Items']())['Add'](comboBoxItem49);
      (comboBox['get_Items']())['Add'](comboBoxItem50);
      (comboBox['get_Items']())['Add'](comboBoxItem51);
      (comboBox['get_Items']())['Add'](comboBoxItem52);
      (comboBox['get_Items']())['Add'](comboBoxItem53);
      (comboBox['get_Items']())['Add'](comboBoxItem54);
      (comboBox['get_Items']())['Add'](comboBoxItem55);
      (comboBox['get_Items']())['Add'](comboBoxItem56);
      (comboBox['get_Items']())['Add'](comboBoxItem57);
      (comboBox['get_Items']())['Add'](comboBoxItem58);
      (comboBox['get_Items']())['Add'](comboBoxItem59);
      (comboBox['get_Items']())['Add'](comboBoxItem60);
      (comboBox['get_Items']())['Add'](comboBoxItem61);
      (comboBox['get_Items']())['Add'](comboBoxItem62);
      (comboBox['get_Items']())['Add'](comboBoxItem63);
      (comboBox['get_Items']())['Add'](comboBoxItem64);
      (comboBox['get_Items']())['Add'](comboBoxItem65);
      (comboBox['get_Items']())['Add'](comboBoxItem66);
      (comboBox['get_Items']())['Add'](comboBoxItem67);
      (comboBox['get_Items']())['Add'](comboBoxItem68);
      (comboBox['get_Items']())['Add'](comboBoxItem69);
      (comboBox['get_Items']())['Add'](comboBoxItem70);
      (comboBox['get_Items']())['Add'](comboBoxItem71);
      (comboBox['get_Items']())['Add'](comboBoxItem72);
      (comboBox['get_Items']())['Add'](comboBoxItem73);
      (comboBox['get_Items']())['Add'](comboBoxItem74);
      (comboBox['get_Items']())['Add'](comboBoxItem75);
      (comboBox['get_Items']())['Add'](comboBoxItem76);
      (comboBox['get_Items']())['Add'](comboBoxItem77);
      (comboBox['get_Items']())['Add'](comboBoxItem78);
      (comboBox['get_Items']())['Add'](comboBoxItem79);
      (comboBox['get_Items']())['Add'](comboBoxItem80);
      (comboBox['get_Items']())['Add'](comboBoxItem81);
      (comboBox['get_Items']())['Add'](comboBoxItem82);
      (comboBox['get_Items']())['Add'](comboBoxItem83);
      var comboBox2 = new ($T24())();
      $T1E().prototype['RegisterName'].call(this, "FilterSign", comboBox2);
      comboBox2['set_Name']("FilterSign");
      $T15()['SetColumn'](comboBox2, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      (comboBox2.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "7"))['MemberwiseClone']());
      var comboBoxItem84 = new ($T26())();
      comboBoxItem84['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\u2265"));
      var comboBoxItem85 = new ($T26())();
      comboBoxItem85['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, ">"));
      var comboBoxItem86 = new ($T26())();
      comboBoxItem86['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "="));
      var comboBoxItem87 = new ($T26())();
      comboBoxItem87['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "<"));
      var comboBoxItem88 = new ($T26())();
      comboBoxItem88['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\u2264"));
      (comboBox2['get_Items']())['Add'](comboBoxItem84);
      (comboBox2['get_Items']())['Add'](comboBoxItem85);
      (comboBox2['get_Items']())['Add'](comboBoxItem86);
      (comboBox2['get_Items']())['Add'](comboBoxItem87);
      (comboBox2['get_Items']())['Add'](comboBoxItem88);
      var textBox = new ($T0D())();
      $T1E().prototype['RegisterName'].call(this, "FilterValue", textBox);
      textBox['set_Name']("FilterValue");
      $T15()['SetColumn'](textBox, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "2")));
      (textBox.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "7"))['MemberwiseClone']());
      var button = new ($T27())();
      button['add_Click']($T29()['New'](this, $thisType.prototype['FilterSet_Click'], function () { return JSIL.GetMethodInfo($thisType, "FilterSet_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      $T15()['SetColumn'](button, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "3")));
      (button.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "2,7"))['MemberwiseClone']());
      button['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "+"));
      (grid4['get_Children']())['Add'](comboBox);
      (grid4['get_Children']())['Add'](comboBox2);
      (grid4['get_Children']())['Add'](textBox);
      (grid4['get_Children']())['Add'](button);
      var grid5 = new ($T15())();
      $T15()['SetRow'](grid5, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      var rowDefinition13 = new ($T18())();
      (rowDefinition13.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "5*"))['MemberwiseClone']());
      var rowDefinition14 = new ($T18())();
      (rowDefinition14.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "2*"))['MemberwiseClone']());
      (grid5['get_RowDefinitions']())['Add'](rowDefinition13);
      (grid5['get_RowDefinitions']())['Add'](rowDefinition14);
      var scrollViewer = new ($T2A())();
      var listBox = new ($T2B())();
      $T1E().prototype['RegisterName'].call(this, "FilterList", listBox);
      listBox['set_Name']("FilterList");
      listBox['set_IsEnabled']($T03().$Cast($T17()['ConvertFromInvariantString']($T03().__Type__, "False")));
      (listBox.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "7"))['MemberwiseClone']());
      scrollViewer['set_Content'](listBox);
      var comboBox3 = new ($T24())();
      $T1E().prototype['RegisterName'].call(this, "FilterListCombo", comboBox3);
      comboBox3['set_Name']("FilterListCombo");
      $T15()['SetRow'](comboBox3, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      (comboBox3.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "20,7"))['MemberwiseClone']());
      (grid5['get_Children']())['Add'](scrollViewer);
      (grid5['get_Children']())['Add'](comboBox3);
      var grid6 = new ($T15())();
      $T15()['SetRow'](grid6, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "2")));
      var columnDefinition7 = new ($T1B())();
      (columnDefinition7.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition8 = new ($T1B())();
      (columnDefinition8.Width = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid6['get_ColumnDefinitions']())['Add'](columnDefinition7);
      (grid6['get_ColumnDefinitions']())['Add'](columnDefinition8);
      var button2 = new ($T27())();
      button2['add_Click']($T29()['New'](this, $thisType.prototype['StartBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "StartBtn_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      (button2.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "15,7"))['MemberwiseClone']());
      button2['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uac80\uc0c9"));
      var button3 = new ($T27())();
      $T15()['SetColumn'](button3, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      button3['add_Click']($T29()['New'](this, $thisType.prototype['DeleteFilterBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DeleteFilterBtn_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      (button3.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "15,7"))['MemberwiseClone']());
      button3['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\ud544\ud130 \uc0ad\uc81c"));
      (grid6['get_Children']())['Add'](button2);
      (grid6['get_Children']())['Add'](button3);
      (grid3['get_Children']())['Add'](grid4);
      (grid3['get_Children']())['Add'](grid5);
      (grid3['get_Children']())['Add'](grid6);
      var grid7 = new ($T15())();
      $T15()['SetRow'](grid7, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "2")));
      var rowDefinition15 = new ($T18())();
      (rowDefinition15.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "6*"))['MemberwiseClone']());
      var rowDefinition16 = new ($T18())();
      (rowDefinition16.Height = $T19().$Cast($T17()['ConvertFromInvariantString']($T19().__Type__, "*"))['MemberwiseClone']());
      (grid7['get_RowDefinitions']())['Add'](rowDefinition15);
      (grid7['get_RowDefinitions']())['Add'](rowDefinition16);
      var scrollViewer2 = new ($T2A())();
      var listBox2 = new ($T2B())();
      $T1E().prototype['RegisterName'].call(this, "ResultBox", listBox2);
      listBox2['set_Name']("ResultBox");
      listBox2['set_IsEnabled']($T03().$Cast($T17()['ConvertFromInvariantString']($T03().__Type__, "False")));
      (listBox2.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "7"))['MemberwiseClone']());
      scrollViewer2['set_Content'](listBox2);
      var comboBox4 = new ($T24())();
      $T1E().prototype['RegisterName'].call(this, "ResultBoxCombo", comboBox4);
      comboBox4['set_Name']("ResultBoxCombo");
      $T15()['SetRow'](comboBox4, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "1")));
      (comboBox4.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "20,7"))['MemberwiseClone']());
      (grid7['get_Children']())['Add'](scrollViewer2);
      (grid7['get_Children']())['Add'](comboBox4);
      var button4 = new ($T27())();
      button4['add_Click']($T29()['New'](this, $thisType.prototype['ShowBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "ShowBtn_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      $T15()['SetRow'](button4, $T04().$Cast($T17()['ConvertFromInvariantString']($T04().__Type__, "3")));
      (button4.Margin = $T25().$Cast($T17()['ConvertFromInvariantString']($T25().__Type__, "45,7"))['MemberwiseClone']());
      button4['set_Content']($T17()['ConvertFromInvariantString']($T05().__Type__, "\uc0c1\uc138\uc635\uc158 \uac80\uc0c9"));
      (grid['get_Children']())['Add'](grid2);
      (grid['get_Children']())['Add'](grid3);
      (grid['get_Children']())['Add'](grid7);
      (grid['get_Children']())['Add'](button4);
      this['set_Content'](grid);
      this.NormCheckBox = checkBox;
      this.NormCheckBoxEx = checkBox2;
      this.WeaponCheckBox = checkBox3;
      this.WeaponCheckBoxEx = checkBox4;
      this.ArmorCheckBox = checkBox5;
      this.ArmorCheckBoxEx = checkBox6;
      this.AdditionalCheckBox = checkBox7;
      this.AdditionalCheckBoxEx = checkBox8;
      this.SpecialCheckBox = checkBox9;
      this.SpecialCheckBoxEx = checkBox10;
      this.FilterOption = comboBox;
      this.FilterSign = comboBox2;
      this.FilterValue = textBox;
      this.FilterList = listBox;
      this.FilterListCombo = comboBox3;
      this.ResultBox = listBox2;
      this.ResultBoxCombo = comboBox4;
    }
  };

  function MainPage_Set_FilterIndex () {
    var flag = (((this.FilterListCombo)['get_Items']())['get_Count']() | 0) > 0;
    if (flag) {
      (this.FilterListCombo)['set_SelectedIndex']((((((this.FilterListCombo)['get_Items']())['get_Count']() | 0) - 1) | 0));
      (this.FilterListCombo)['set_IsEnabled'](true);
    } else {
      (this.FilterListCombo)['set_SelectedIndex'](0);
      (this.FilterListCombo)['set_IsEnabled'](false);
    }
  };

  function MainPage_ShowBtn_Click (sender, e) {
  };

  function MainPage_StartBtn_Click (sender, e) {
    var list = $S04().Construct();
    var i = 0;
    var isChecked = (this.NormCheckBox)['get_IsChecked']();
    var flag2 = (JSIL['Nullable_ValueOrDefault'](isChecked, false) === true) & (isChecked !== null);
    if (flag2) {

      for (var text = this['GetDataFromHub']("http://cors-anywhere.herokuapp.com/https://raw.githubusercontent.com/toramcalculator/crysta/main/normal"); (text.indexOf("\"name\":\"")) !== -1; ) {
        var text2 = "";
        var text3 = "";

        for (var num = (((text.indexOf("\"name\":\"")) + ("\"name\":\"".length | 0)) | 0); ((text[num])['charCodeAt'](0) | 0) !== (("\"")['charCodeAt'](0) | 0); num = ((num + 1) | 0)) {
          text2 = (JSIL.ConcatString(text2, (text[num])['toString']()));
        }

        for (var num2 = (((text.indexOf("\"option\":\"")) + ("\"option\":\"".length | 0)) | 0); ((text[num2])['charCodeAt'](0) | 0) !== (("\"")['charCodeAt'](0) | 0); num2 = ((num2 + 1) | 0)) {
          text3 = (JSIL.ConcatString(text3, (text[num2])['toString']()));
        }
        text = (System.String.Remove(text, text.indexOf("\"name\":\""), "\"name\":\"".length));
        text = (System.String.Remove(text, text.indexOf("\"option\":\""), "\"option\":\"".length));
        list['Add'](new ($T2E())(text2, text3));
      }

      for (; i < (list['get_Count']() | 0); i = ((i + 1) | 0)) {
      }
    }
  };

  JSIL.MakeType({
      BaseType: $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Page"), 
      Name: "Studie.MainPage", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainPage__ctor
    );

    $.Method({Static:false, Public:false}, "CutString", 
      new JSIL.MethodSignature($.String, [
          $.String, $.String, 
          $.String
        ]), 
      MainPage_CutString
    );

    $.Method({Static:false, Public:false}, "DeleteFilterBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_DeleteFilterBtn_Click
    );

    $.Method({Static:false, Public:false}, "FilterSet_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_FilterSet_Click
    );

    $.Method({Static:false, Public:false}, "GetDataFromHub", 
      new JSIL.MethodSignature($.String, [$.String]), 
      MainPage_GetDataFromHub
    );

    $.Method({Static:false, Public:true }, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      MainPage_InitializeComponent
    );

    $.Method({Static:false, Public:false}, "Set_FilterIndex", 
      JSIL.MethodSignature.Void, 
      MainPage_Set_FilterIndex
    );

    $.Method({Static:false, Public:false}, "ShowBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_ShowBtn_Click
    );

    $.Method({Static:false, Public:false}, "StartBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_StartBtn_Click
    );

    $['Field']({Static:false, Public:false}, "NormCheckBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "NormCheckBoxEx", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "WeaponCheckBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "WeaponCheckBoxEx", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "ArmorCheckBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "ArmorCheckBoxEx", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "AdditionalCheckBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "AdditionalCheckBoxEx", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "SpecialCheckBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "SpecialCheckBoxEx", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.CheckBox")); 
    $['Field']({Static:false, Public:false}, "FilterOption", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "FilterSign", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "FilterValue", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "FilterList", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ListBox")); 
    $['Field']({Static:false, Public:false}, "FilterListCombo", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "ResultBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ListBox")); 
    $['Field']({Static:false, Public:false}, "ResultBoxCombo", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* struct Studie.MainPage+CrystaInfo */ 

(function CrystaInfo$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };

  function CrystaInfo__ctor (_name, _option) {
    this.$name = _name;
    this.option = _option;
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.ValueType"), 
      Name: "Studie.MainPage+CrystaInfo", 
      IsPublic: false, 
      IsReferenceType: false, 
      MaximumConstructorArguments: 2, 
      SequentialLayout: true, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [$.String, $.String]), 
      CrystaInfo__ctor
    );

    $['Field']({Static:false, Public:true }, "$name", $.String); 
    $['Field']({Static:false, Public:true }, "option", $.String); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

